export const QUERY_KEYS = {
  GET_COIN_DATA: 'GET_COIN_DATA',
  GET_COIN_BY_ID: 'GET_COIN_BY_ID',
  GET_HISTORY_COIN: 'GET_HISTORY_COIN',
  SEARCH_COIN: 'SEARCH_COIN',
  COIN_REAL_TIME: 'COIN_REAL_TIME',
};
